deployments:
  - name: api
    image: danilkolmahin/ideal-octo-chainsaw
  - name: handler
    image: danilkolmahin/ideal-octo-chainsaw

services:
  - app: api

ingresses:
  - service: api
    host: ideal-octo-chainsaw.xyz
    path: /
