deployments:
  - name: api
    image: danilkolmahin/ideal-octo-chainsaw
    env:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  - name: handler
    image: danilkolmahin/ideal-octo-chainsaw

services:
  - app: api

ingresses:
  - service: api
    host: ideal-octo-chainsaw.xyz
    path: /

secrets:
  - name: database
    data:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
