deployments:
  - name: api
    image: danilkolmahin/ideal-octo-chainsaw
    env:
      PORT: 80
      DATABASE_NAME:
      DATABASE_USER:
      DATABASE_PASSWORD:
  - name: handler
    image: danilkolmahin/ideal-octo-chainsaw
    env:
      PORT: 80
      DATABASE_NAME:
      DATABASE_USER:
      DATABASE_PASSWORD:

services:
  - app: api

ingresses:
  - service: api
    host: ideal-octo-chainsaw.xyz
    path: /

secrets:
  DATABASE_NAME: database
  DATABASE_USER: user
  DATABASE_PASSWORD: password
