deployments:
  - name: api
    image: danilkolmahin/ideal-octo-chainsaw
    env:
      DATABASE_PASSWORD:
      MESSAGE_BROKER_PASSWORD:
      API_PASSWORD:
  - name: handler
    image: danilkolmahin/ideal-octo-chainsaw
    env:
      DATABASE_PASSWORD:
      MESSAGE_BROKER_PASSWORD:

services:
  - app: api

ingresses:
  - service: api
    host: ideal-octo-chainsaw.xyz
    path: /
    clusterIssuer: letsencrypt-prod

secrets:
  DATABASE_PASSWORD:
  MESSAGE_BROKER_PASSWORD:
  API_PASSWORD:
