apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: danilkolmahin/ideal-octo-chainsaw:api-0.1.0
        name: ideal-octo-chainsaw
        resources: {}
        # imagePullPolicy: Always
        # ports:
        #   - containerPort: 80
        # env:
        #   - name: PORT
        #     value: "80"
status: {}
