apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: danilkolmahin/ideal-octo-chainsaw:api-0.1.0
        name: ideal-octo-chainsaw
