apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-broker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.11-managment-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: dev
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MESSAGE_BROKER_PASSWORD
          volumeMounts:
            - name: message-broker
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: message-broker
          persistentVolumeClaim:
            claimName: message-broker
---
apiVersion: v1
kind: Service
metadata:
  name: message-broker
spec:
  type: ClusterIP
  ports:
    - port: 5672
  selector:
    app: message-broker
