name: CI-CD

on:
  push: 
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - run: npm i
      - run: echo "VERSION=$(npm pkg get version | tr -d \")" >> $GITHUB_ENV
      - run: VERSION=${{ env.VERSION }} npm run build-projects
      - uses: docker/login-action@v3
        with:
          username: danilkolmahin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push danilkolmahin/ideal-octo-chainsaw -a
      - run: |
          curl -Lo ./res.tar.gz https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
          tar -zxvf res.tar.gz
          mv linux-amd64/helm /usr/local/bin
      - run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          helm upgrade -i -f values.yaml --set version=${{ env.VERSION }} --kubeconfig $HOME/.kube/config ideal-octo-chainsaw .
